### ISSUE TITLE
Availability of assoc command

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#18]
At the present moment, only server owner have access to assoc command.
It's done for security reasons, so `@MrShadowMaster` can't pretend to be a `GreatMan11`
And can't get op for this nick (he still can log in with this name, btw).
But, what if play in-game could have an assoc request with dialog, like this:
Hey, GreatMan11, guy from Discord (MrShadowMaster) tell's us, that you're the same person, is it True?
[YES] / [NO]
and click on each button will insert text like
%yes I'm MrShadowMaster and %no I'm not
So from discord you as default (non-admin) user use %assoc GreatMan11 command
(yup, I mean your id used if no-one else mentioned) and you get request in-game, so after confirmation the process will end up ast it was with admin rights :)

**Comment by Druzai** [comment]
> At the present moment, only server owner have access to assoc command.

After 8 month... 😄
You can now set role `Administrator` for bot and add selected members, so I think this problem solved now.

**Comment by MaxBQb** [comment]
Actually this is different features :)
