### ISSUE TITLE
Backup feature

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#21]
Backup
1. Set current state to create backup (prevent from stop/start)
2. Test Rcon connection (if running)
3. Dump current state (/save-all) ..wait.. (if running)
4. Check for free space
5. Check for amount limitation
6. Ask user for remove backup if nessessary because of space-limit
7. Retry check (if no backups for remove, thow NotEnoughtSpace warning)
8. Create archive
9. Remove oldest backup if max_limit exceeded
10. Save info about backup

Restore
1. Check for backup availability
2. Check for free space
3. Check for access
4. Stop server
5. Archive current world Reason: Restore from `date time`
6. Unpack backup
7. Start server if needed

**Comment by Druzai** [comment]
Implemented in new release
