### ISSUE TITLE
Mentions from minecraft to discord

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#25]
I find out, that `@a` has effect as announce for everyone
while it must tag only minecrafters.

So, Full list:
| Minecraft | Discord |
|------------|----------|
| `@a` | `@Minecrafters` |
| `@all` | `@Minecrafters` |
| `@e` | `@everyone` |
| `@p` | `@here` |
| `@here` | `@here` |
| `@everyone` | `@everyone` |
| `@AnyRoleOrMention` | `@SameRoleOrMention` |

**Comment by Druzai** [comment]
Firstly, role `Minecrafter` isn't defined in bot's config.
You're suggesting to add it and setting to setup it via bot command roles?

**Comment by Druzai** [comment]
@MaxBQb I'd like your answer for my last comment

**Comment by MaxBQb** [comment]
Em.. Instead of write my comment.. github override yours 👍 )

**Comment by MaxBQb** [comment]
Anyway,  it is "quality of live" suggestion, I think, with normal priority, rather then low priority (because low often means never)

**Comment by Druzai** [comment]
Eh, I can add it, it not big feature :)

**Comment by MaxBQb** [comment]
You may also separate tasks like this:
Complexity: Hard | Medium | Easy
Time limits: Needed right now | Can wait | May stay not implemented forever
Amount of profit: Critical | Way more better | Better then nothing | No difference

**Comment by MaxBQb** [comment]
For this task it is:
`Easy`, `Can wait`, `Better then nothing`
For me
And may be `Way more better` for those who don't playing minecraft but stay still on discord server.

**Comment by MaxBQb** [comment]
Well.. they can find workarounds also.. that's why it can wait.. and.. 
Potentially forever :(
