### ISSUE TITLE
Fast-login feature

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#26]
Use of `%auth login my_nick`
With no code provided
will trigger next behavior:

1. Check if user has **assoc** for this nick (if not, then send "*Code required*")
1. Ask user "*Are you sure, you want to login without code?
This method is less safer (someone could connect right before you).*" 
1. If user accept this, then bot gives access for the last attempted ip

So, users must deal with balancing between safe and ease by themselves

**Comment by MaxBQb** [comment]
For safety, u can reply exact request :)

**Comment by MaxBQb** [comment]
Alternatively u may use tokens :)

**Comment by MaxBQb** [comment]
Or just use polls in DMs)

**Comment by Druzai** [comment]
Done!
