### ISSUE TITLE
Minecraft last message edit

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#27]
If message in minecraft starts with * sign
Then last message in discord from this player will edited 
to accomplish with that message

Example:
`Helow jokobaba`
`*Hello jokobaba`
`*Hello, jokobaba`

In discord must looks like:
![image](https://user-images.githubusercontent.com/27343275/147813226-bba49488-001e-45a1-a0a7-9594090850c1.png)

**Comment by MaxBQb** [comment]
For edit from discord `%edit` maybe :)

changes text of message in reply, but only if you are the owner of that message

Is it even possible?

**Comment by Druzai** [comment]
Yea, it's possible. Ownership bot must check via `assoc`?

**Comment by MaxBQb** [comment]
Well in mc chat answer is yes
But for `%transfer`.. things get complicated :)

**Comment by Druzai** [comment]
Also this question: when message of webhook gets edited, bot will have to send this edited message to minecraft chat like this or not?
![image](https://user-images.githubusercontent.com/70586473/150864449-2893df08-4156-4a8d-9f3d-c6daadae0eef.png)

**Comment by MaxBQb** [comment]
Well, first of all, this message edition is started from minecraft so in minecraft chat we already have something like
```
<MrDioDay> Helo there // Message from game
<MrDioDay> *Hello there! // Message from game
// Leads to only one edited message in discord
<MrDioDay> Hello there!
```
So there is no need in duplication in this case

For eddition from discord, the answer is yes
It wil looks like this:
```
<MrDioDay> Helo there // Message from game
<MrDioDay> *Hello there! // Message from Discord with mention of previous text version
// Removes %edit call, so in discord it is also only one message
<MrDioDay> Hello there!
```

**Comment by Druzai** [comment]
> If message in minecraft starts with * sign
Then last message in discord from this player will edited
to accomplish with that message

From your first comment on this issue.
Question is how sensitive search for that message must be?

For example: you send message in minecraft via webhook yesterday. Today when you accidentally send message in minecraft with one `*` at the start of your message, bot will edit that message in discord from yesterday...
Maybe last message mustn't be older than 12 or 24 hours?

**Comment by MaxBQb** [comment]
From minecraft: 5 hours is more than enough
From discord with the help of %edit - no limitations

Also... when server restarts.. there is no need to provide this kind of edition (in game)
So, may be you should ignore * in this case and simply send this full text. (there is no such limitation for %edit)
Example:
Minecraft
```
<MrDioDay> Helo there
// Server stoped
// ... 
// Server started
<MrDioDay> *Hello there!
```
Discord
```
<MrDioDay> Helo there
<MrDioDay> *Hello there!
```

Tip: You can compare last message send date with server startup date, but ensure there is the same timezone :)

**Comment by Druzai** [comment]
All done!

> Tip: You can compare last message send date with server startup date, but ensure there is the same timezone :)

Yea, it was interesting :)
