### ISSUE TITLE
Ошибка идентификации состояния

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#3]
Прошу переписать механизм отслеживания состояния сервера, 
сделать свойство **IsServerOn** вычислимым, добавить в геттер свойства функцию запроса на сервер.. работает ли он.
Пример свойства и задания геттера через декоратор
https://www.geeksforgeeks.org/getter-and-setter-in-python/

Можешь так же закешировать свойство:
Например храня время последнего запроса, можно возвращять его результат, в случае, если с последнего запроса прошло не очень много времени.

**Comment by MaxBQb** [comment]
Проблема в том, что сервер лёг уже и спит.. а бот ещё какое-то время верит, что серв жив)

**Comment by AlluSoN** [comment]
Исправлено в последнем коммите
