### ISSUE TITLE
Предложение: состояние дня/ночи на сервере

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#4]
Добавить команду и кнопку для получения информации о времени суток на сервере.
Формат: **Сейчас на сервере утро/день/вечер/ночь**
Опционально можно указать время как HH:mm в статье была формула расчёта для этого.
Команда получения времени в тиках _/time query daytime_
статья про цикл дня/ночи
https://minecraft-ru.gamepedia.com/%D0%A6%D0%B8%D0%BA%D0%BB_%D0%B4%D0%BD%D1%8F_%D0%B8_%D0%BD%D0%BE%D1%87%D0%B8

**Comment by AlluSoN** [comment]
Добавлено
