### ISSUE TITLE
Предложение: Механизм force load

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#8]
Командой forceload on/off
можно задействовать механизм
Суть: если бот выясняет, что сервер лежит, а forceload = true,  
то сервер запускается автоматически.

P. S. Учесть, что всё время, пока сервер стартует, он так-то тоже выключен, но это не повод для force load.

**Comment by AlluSoN** [comment]
Сделаю, по постскриптуму: такая переменная уже есть)

**Comment by AlluSoN** [comment]
Добавлено
